Repository DeliverBle/deliverble-backend, pull requests merged in 2022-07, with the labels that each got.

#4 [#2] 도메인 초기 설계
  .prettierrc.js
  ormconfig.json
  package-lock.json
  package.json
  src/entity/News.ts
  src/entity/Tag.ts
  src/index.ts
  src/repository/NewsRepository.ts
  src/shared/common/Category.ts
  src/shared/common/Gender.ts
  src/shared/common/Suitability.ts
  src/types.ts
  src/vo/Time.ts
  tsconfig.json
Labels: 1순위

#11 style: prettier added
  .idea/workspace.xml
  .prettierrc.js
  src/controllers/NewsController.ts
  src/controllers/index.ts
  src/index.ts
  src/modules/responseMessage.ts
  src/modules/statusCode.ts
  src/modules/util.ts
  src/repository/NewsRepository.ts
  src/routes/NewsRouter.ts
  src/routes/index.ts
  src/service/NewsService.ts
  src/service/index.ts
  src/shared/common/Channel.ts
Labels: enhancement

#32 News 리스트를 품은 User 객체를 생성한다.
  src/entity/User.ts
  src/index.ts
  src/shared/common/Gender.ts
  src/util/MockUserToFavorite.ts
Labels: 2순위

#37 카카오 소셜 로그인 및 로그아웃 기능을 구현한다.
  .redis_standalone.yml.swp
  package-lock.json
  package.json
  redis_standalone.yml
  src/controllers/UserController.ts
  src/controllers/kakao-login.ts
  src/entity/NotFoundUser.ts
  src/entity/User.ts
  src/error/AccessTokenExpiredError.ts
  src/error/AlreadyLoggedOutError.ts
  src/error/CustomError.ts
  src/error/ErrorHandler.ts
  src/error/UserNotFoundError.ts
  src/index.ts
  src/modules/responseMessage.ts
  src/repository/UserCommandRepository.ts
  src/repository/UserQueryRepository.ts
  src/routes/index.ts
  src/routes/kakaoRouter.ts
  src/service/UserService.ts
  src/shared/AuthLink.ts
  src/types.ts
  src/util/redis.ts
Labels: 2순위

#47 refactor #39: add gender specification on service
  src/entity/User.ts
  src/shared/common/Gender.ts
  src/types.ts
Labels: bug, 2순위

#93 Memo를 구현한다 Issue #92
  src/controllers/HighlightController.ts
  src/entity/Highlight.ts
  src/entity/Memo.ts
  src/modules/responseMessage.ts
  src/repository/HighlightCommandRepository.ts
  src/repository/HighlightRepository.ts
  src/repository/MemoRepository.ts
  src/routes/HighlightRouter.ts
  src/service/HighlightService.ts
  src/service/NewsService.ts
  src/service/UserService.ts
  src/types.ts
  src/vo/MemoArrayWrappedObject.ts
Labels: enhancement, 2순위

#95 Spacing을 구현한다. Issue #80
  dump.rdb
  src/controllers/SpacingController.ts
  src/entity/Spacing.ts
  src/entity/User.ts
  src/index.ts
  src/modules/responseMessage.ts
  src/repository/SpacingCommandRepository.ts
  src/repository/SpacingQueryRepository.ts
  src/routes/SpacingRouter.ts
  src/routes/index.ts
  src/service/SpacingService.ts
  src/service/UserService.ts
  src/shared/common/Gender.ts
  src/types.ts
Labels: enhancement, 2순위
